import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "CRUD App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased container mx-auto">
      <Toaster />
        <nav className="bg-background shadow-md">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between items-center py-3 md:justify-start md:space-x-10">
              <div className="flex justify-start lg:w-0 lg:flex-1">
                <Link href="/" className="text-xl font-bold text-white">CRUD App</Link>
              </div>
              <div className="hidden md:flex items-center justify-end md:flex-1 lg:w-0">
                <ul className="flex space-x-4">
                  <li className="text-base font-medium text-white hover:bg-white hover:text-background px-3 py-2 rounded-md">
                    <Link href="/about">About</Link>
                  </li>
                  <li className="text-base font-medium text-white hover:bg-white hover:text-background px-3 py-2 rounded-md">
                    <Link href="/posts">Posts</Link>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </nav>

        {children}
      </body>
  </html>

  );
}
